In [88]:
import cv2
import h5py

import numpy as np
import random

In [89]:
# import os
# dir = r"C:\Users\vrinda\Documents\GitHub\computer-vision-hands-on\Problem\dataset\Wood Dataset\Test"
# images, names = [], []
# for img_name in os.listdir(dir):
#     img_path = dir+'\\'+img_name
#     img = cv2.imread(img_path)
#     images.append(img)
#     names.append(img_name)

In [90]:
# import random
# # random.shuffle(zip(images,names))
# l=list(zip(images,names))
# random.shuffle(l)

In [91]:
# l[2]

In [92]:
# with h5py.File(r'C:\Users\vrinda\Documents\GitHub\computer-vision-hands-on\Problem\dataset\wood_species_train.hdF5','w') as f:
#     dset = f.create_dataset('images',data=images)
#     dset = f.create_dataset('labels',data=labels)

In [93]:
# pip install opencv-python

In [94]:
# pip install h5py

In [95]:
# l1 = [1,2,3]
# l2 = [4,5,6]
# zl = list(zip(l1,l2))
# uzl = list(zip(*zl))
# print(uzl)
# k=list(uzl[0])
# k

In [96]:
train_data = r'C:\Users\vrinda\Documents\GitHub\computer-vision-hands-on\Problem\dataset\wood_species_train.hdF5'
with h5py.File(train_data) as f:
    imgs = f['images'][:]
    labels = f['labels'][:]
    
print(imgs.shape,labels.shape)
print(imgs)
labels[2]

(5708, 200, 200, 3) (5708,)
[[[[180 177 169]
   [187 184 176]
   [193 190 182]
   ...
   [162 159 155]
   [166 163 159]
   [172 169 165]]

  [[179 176 168]
   [185 182 174]
   [191 188 180]
   ...
   [163 160 156]
   [167 164 160]
   [173 170 166]]

  [[178 175 167]
   [182 179 171]
   [187 184 176]
   ...
   [165 162 158]
   [168 165 161]
   [174 171 167]]

  ...

  [[182 179 171]
   [177 174 166]
   [173 170 162]
   ...
   [177 175 165]
   [173 171 161]
   [171 169 159]]

  [[178 175 167]
   [174 171 163]
   [172 169 161]
   ...
   [176 174 164]
   [174 172 162]
   [174 172 162]]

  [[173 170 162]
   [171 168 160]
   [170 167 159]
   ...
   [176 174 164]
   [175 173 163]
   [178 176 166]]]


 [[[163 161 161]
   [162 160 160]
   [161 159 159]
   ...
   [186 178 165]
   [190 181 168]
   [193 184 171]]

  [[162 160 160]
   [161 159 159]
   [161 159 159]
   ...
   [186 178 165]
   [189 180 167]
   [191 182 169]]

  [[161 159 159]
   [161 159 159]
   [161 159 159]
   ...
   [186 178 165]


1

In [97]:
# zip(imgs,labels)
# td = list(zip(imgs,labels))
# random.shuffle(td)
print(imgs[500])

[[[167 163 162]
  [165 161 160]
  [163 161 160]
  ...
  [168 171 169]
  [160 163 161]
  [153 156 154]]

 [[170 166 165]
  [170 166 165]
  [169 167 166]
  ...
  [173 176 174]
  [170 173 171]
  [166 169 167]]

 [[169 165 164]
  [171 167 166]
  [171 169 168]
  ...
  [173 176 174]
  [176 179 177]
  [176 179 177]]

 ...

 [[153 149 148]
  [154 150 149]
  [155 151 150]
  ...
  [163 163 163]
  [165 165 165]
  [167 167 167]]

 [[157 154 150]
  [159 156 152]
  [161 158 154]
  ...
  [162 162 162]
  [162 162 162]
  [163 163 163]]

 [[164 161 157]
  [167 164 160]
  [169 166 162]
  ...
  [159 159 159]
  [158 158 158]
  [157 157 157]]]


In [98]:
# i = 500
# cv2.imshow(str(labels[500]),imgs[500])
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [99]:
# train_img = list(paths.list_images(r"C:\Users\vrinda\Documents\GitHub\computer-vision-hands-on\Problem\dataset\Wood Dataset\Test"))
# # train_img = np.array(train_img)
# train_img

In [100]:
from sklearn.model_selection import train_test_split 
(trainX, testX, trainY, testY) = train_test_split(imgs,labels, test_size=0.25) 

In [101]:
print(len(testY))
print(len(testX))


1427
1427


In [102]:
print(trainY.shape)

(4281,)


In [103]:
sift = cv2.xfeatures2d.SIFT_create()
trainX_descriptors = []
none_idx = []
for i,img in enumerate(trainX):
    image =cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    key,desc = sift.detectAndCompute(image,None)
    try:
        notnone = desc.any()
        trainX_descriptors.append(desc)
    except:
        none_idx.append(i)


print(trainX_descriptors)



[array([[  8., 110.,  54., ...,   0.,   0.,   0.],
       [  9.,  56.,  42., ...,   0.,   0.,   0.],
       [  1.,   8., 103., ...,   0.,   0.,   0.],
       ...,
       [  2.,   1.,   1., ...,   2.,   1.,   4.],
       [ 33.,   0.,   0., ...,   0.,   0.,   2.],
       [ 10.,  35., 114., ...,   0.,   0.,   0.]], dtype=float32), array([[153.,  32.,   2., ...,   0.,   0.,   0.],
       [ 26.,   3.,   0., ...,   0.,   0.,   0.],
       [ 21.,   6.,   2., ...,   0.,   0.,   0.],
       ...,
       [ 49.,  11.,   6., ...,   6.,   1.,   3.],
       [  0.,   0.,   0., ...,  31.,   3.,   5.],
       [  0.,   0.,   0., ...,  10.,   8.,  12.]], dtype=float32), array([[ 7.,  3.,  1., ...,  0.,  0.,  0.],
       [ 5.,  0.,  0., ...,  8.,  2.,  1.],
       [ 3.,  0.,  0., ..., 74.,  7.,  3.],
       ...,
       [ 0.,  0.,  0., ...,  2.,  0.,  4.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [12.,  6.,  2., ...,  0.,  0.,  0.]], dtype=float32), array([[14.,  0.,  0., ..., 20.,  1., 10.],
    

In [104]:
print((none_idx))

[10, 17, 18, 24, 28, 33, 113, 159, 166, 168, 188, 204, 207, 229, 243, 247, 259, 262, 268, 271, 292, 296, 299, 310, 315, 318, 325, 331, 333, 335, 347, 352, 360, 373, 377, 389, 403, 404, 412, 426, 430, 442, 449, 465, 468, 470, 473, 478, 488, 489, 490, 494, 500, 536, 538, 544, 558, 585, 586, 607, 617, 641, 644, 645, 651, 667, 668, 680, 698, 702, 705, 716, 753, 760, 769, 771, 778, 801, 816, 831, 838, 839, 845, 854, 860, 863, 864, 878, 881, 885, 888, 902, 911, 921, 936, 951, 975, 977, 978, 997, 998, 1000, 1026, 1029, 1034, 1045, 1056, 1061, 1081, 1094, 1099, 1103, 1104, 1106, 1118, 1132, 1140, 1145, 1147, 1153, 1159, 1164, 1180, 1183, 1194, 1200, 1216, 1218, 1233, 1247, 1254, 1256, 1263, 1270, 1271, 1274, 1294, 1316, 1321, 1331, 1333, 1334, 1340, 1349, 1375, 1384, 1397, 1398, 1401, 1417, 1423, 1429, 1439, 1440, 1442, 1455, 1476, 1478, 1479, 1486, 1495, 1499, 1507, 1511, 1514, 1518, 1529, 1533, 1539, 1541, 1570, 1571, 1577, 1594, 1610, 1613, 1616, 1630, 1636, 1662, 1669, 1681, 1689, 1693, 16

In [105]:
trainynon=[]
for i in range(len(trainY)):
    if i not in none_idx:
        trainynon.append(trainY[i])

In [106]:
print(len(trainynon))

3784


In [107]:
fitX_descriptors=np.vstack(trainX_descriptors)

In [108]:
print(type(fitX_descriptors))

<class 'numpy.ndarray'>


In [122]:
from sklearn.cluster import KMeans 
kmeans = KMeans(n_clusters =300,init = 'k-means++')
kmeans.fit(fitX_descriptors)

c:\Users\vrinda\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=300)

In [142]:
import pickle
pickle.dump(kmeans, open('kmeanmodel.pkl', 'wb'))

In [143]:
print(len(trainX_descriptors))

3784


In [144]:

hist_list =[]
for i in trainX_descriptors:
    PRED = kmeans.predict(i)
    histogram, _ = np.histogram(PRED, bins=5)
    hist_list.append(histogram)
print("Histogram:", hist_list)   
print(i.shape)    

Histogram: [array([32, 37, 42, 37, 45], dtype=int64), array([21, 24,  2, 14,  7], dtype=int64), array([19, 18, 24, 21, 23], dtype=int64), array([11, 18, 17, 14, 22], dtype=int64), array([126, 149, 156,  99, 157], dtype=int64), array([131,  75,  61, 126,  67], dtype=int64), array([ 83, 110, 145,  82, 110], dtype=int64), array([ 93, 104, 102,  73, 100], dtype=int64), array([156, 175, 128, 148, 201], dtype=int64), array([138,  91,  66, 123,  89], dtype=int64), array([14,  8, 19, 12, 11], dtype=int64), array([67, 87, 85, 84, 93], dtype=int64), array([3, 0, 0, 2, 1], dtype=int64), array([ 4,  8, 10,  8,  5], dtype=int64), array([27,  6, 21, 27, 22], dtype=int64), array([ 8, 42, 20, 32, 11], dtype=int64), array([ 7,  2, 12,  7,  9], dtype=int64), array([1, 0, 1, 3, 1], dtype=int64), array([1, 0, 0, 0, 1], dtype=int64), array([17,  8, 11,  4,  2], dtype=int64), array([11, 11,  8, 19,  6], dtype=int64), array([148, 125, 113, 138, 156], dtype=int64), array([1, 0, 2, 0, 1], dtype=int64), array([

In [145]:
from sklearn.preprocessing import StandardScaler
stdslr=StandardScaler().fit(hist_list)
hist_list=stdslr.transform(hist_list)

In [146]:
print(len(hist_list))

3784


In [147]:
print(len(trainY))

4281


In [155]:
from sklearn.svm import LinearSVC
clf=LinearSVC(max_iter=200000)
clf.fit(hist_list,trainynon)

LinearSVC(max_iter=200000)

In [156]:
testX_descriptors = []
none_test =[]
for i,img in enumerate(testX):
    key,desc =sift.detectAndCompute(img,None)
    try:
        notnone = desc.any()
        testX_descriptors.append(desc)
    except:
        none_test.append(i)



In [162]:
testynon=[]
for i in range(len(testY)):
    if i not in none_test:
        testynon.append(testY[i])

In [163]:
hist_test =[]
for i in testX_descriptors:
    PRED = kmeans.predict(i)
    histogram, _ = np.histogram(PRED, bins=5)
    hist_test.append(histogram)
print("Histogram:", hist_test)   
 

Histogram: [array([140, 198, 153, 133, 151], dtype=int64), array([96, 41, 38, 74, 50], dtype=int64), array([ 94, 128, 136, 120, 158], dtype=int64), array([16,  7, 11, 31,  6], dtype=int64), array([69, 72, 32, 62, 64], dtype=int64), array([15, 21, 34, 23, 27], dtype=int64), array([1, 5, 4, 7, 6], dtype=int64), array([3, 0, 1, 3, 3], dtype=int64), array([261, 250, 230, 254, 193], dtype=int64), array([4, 2, 2, 4, 5], dtype=int64), array([3, 0, 4, 2, 2], dtype=int64), array([41, 47, 41, 44, 39], dtype=int64), array([5, 1, 0, 4, 2], dtype=int64), array([13, 10, 10, 12, 17], dtype=int64), array([5, 2, 2, 3, 3], dtype=int64), array([11,  9,  1, 15,  5], dtype=int64), array([1, 1, 1, 1, 4], dtype=int64), array([6, 2, 4, 5, 6], dtype=int64), array([24,  9, 12, 21, 17], dtype=int64), array([ 92,  60,  67, 110,  73], dtype=int64), array([3, 0, 2, 1, 2], dtype=int64), array([49, 43, 44, 50, 60], dtype=int64), array([49, 46, 65, 46, 67], dtype=int64), array([ 9,  2,  7, 11,  4], dtype=int64), array

In [164]:
hist_test=stdslr.transform(hist_test)

In [165]:
TEST= clf.predict(hist_test)
print(len(TEST))

1268


In [169]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy=accuracy_score(testynon,TEST)
print(accuracy*100)

26.97160883280757
